### ISSUE TITLE
Confd giving a 501 peers not reachable single node etcd

### ISSUE THREAD

**Issue by nickfleming** [kelseyhightower/confd#152]
I am running confd in a docker container, with the docker host running etcd. I am able to get values from etcdctl as well as curl, but confd gives the 501: All the given peers are not reachable.
Bash script (for testing) running inside the container:

```
#!/bin/bash
/usr/global/apps/etcdctl --no-sync -peers http://172.17.42.1:4001 ls system/zookeeper
echo "curl test: " $(curl -X GET http://172.17.42.1:4001/v2/keys/system/zookeeper?consistent=true&recursive=false&sorted=false)
/usr/global/apps/confd -onetime=true -verbose=true -debug=true -node="172.17.42.1:4001" -confdir=/usr/global/config/shared/zookeeper/confd/
```

And here is the output I am getting:

```
/system/zookeeper/zookeeper-1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   294    0   294    0     0   169k      0 --:--:-- --:--:-- --:--:--  287k
test:  {"action":"get","node":{"key":"/system/zookeeper","dir":true,"nodes":[{"key":"/system/zookeeper/zookeeper-1","value":"{\"id\":\"1\",\"ip\":\"10.1.51.252\",\"cport\":\"49153\",\"pport\":\"49154\",\"lport\":\"49155\"}","modifiedIndex":30,"createdIndex":30}],"modifiedIndex":29,"createdIndex":29}}
2014-10-15T12:54:51-04:00 78d09c06c9fc /usr/global/apps/confd[16]: WARNING Skipping confd config file.
2014-10-15T12:54:51-04:00 78d09c06c9fc /usr/global/apps/confd[16]: NOTICE Backend set to etcd
2014-10-15T12:54:51-04:00 78d09c06c9fc /usr/global/apps/confd[16]: NOTICE Starting confd
2014-10-15T12:54:51-04:00 78d09c06c9fc /usr/global/apps/confd[16]: NOTICE Backend nodes set to 172.17.42.1:4001
2014-10-15T12:54:51-04:00 78d09c06c9fc /usr/global/apps/confd[16]: DEBUG Loading template resources from confdir /usr/global/config/shared/zookeeper/confd/
2014-10-15T12:54:51-04:00 78d09c06c9fc /usr/global/apps/confd[16]: DEBUG Processing template resource /usr/global/config/shared/zookeeper/confd/conf.d/zookeeperconf.toml
2014-10-15T12:54:51-04:00 78d09c06c9fc /usr/global/apps/confd[16]: DEBUG Loading template resource from /usr/global/config/shared/zookeeper/confd/conf.d/zookeeperconf.toml
2014-10-15T12:54:51-04:00 78d09c06c9fc /usr/global/apps/confd[16]: ERROR 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
2014-10-15T12:54:51-04:00 78d09c06c9fc /usr/global/apps/confd[16]: DEBUG Retrieving keys from store
2014-10-15T12:54:51-04:00 78d09c06c9fc /usr/global/apps/confd[16]: DEBUG Key prefix set to /
```

The top two lines show the correct ip and port are being used (unlike https://github.com/kelseyhightower/confd/issues/130)
versions:
etcd version 0.4.5
etcdctl version 0.4.5
confd 0.6.3

**Comment by treed** [comment]
I am also having this issue with both addr and bind_addr set appropriately, on etcd 0.4.6.

Hopefully 0.5.0 will be out soon?

**Comment by bacongobbler** [comment]
you may want to see if #195 applies and if #198 fixes your problem. It could be that confd is being built with go-etcd from master.

**Comment by treed** [comment]
I don't think #195 applies, but #198 seems plausible. I'll watch that thread, thanks.

**Comment by nickfleming** [comment]
After updating to the latest release (version 2.0.3) of etcd, this was fixed using the "-advertise-client-urls" flag in addition to the "-listen-client-urls" flag. If you are using the 0.4.x version, you need both the "-addr" and "-bind-addr" flags.

**Comment by treed** [comment]
I built my own copy of the pull request branch from #198, but I'm still getting the same error. :-/

**Comment by bacongobbler** [comment]
@treed any feedback on the PR is greatly appreciated

**Comment by treed** [comment]
Well is #198 really intended to solve this 501 error? If so, I'll can comment on it.

**Comment by bacongobbler** [comment]
right. wrong bug!

**Comment by dieu** [comment]
I have the same problem

**Comment by mingfang** [comment]
I still having this problem using etcd 2.0.9 and confd 0.8.0.
Why is this issue close?

**Comment by bacongobbler** [comment]
@dieu could you please display logs for both confd and etcd, as well as how you invoked confd?

**Comment by agalitsyn** [comment]
I also get this error.

Commands to start etcd container
```sh
docker run -p 4001:4001 -d coreos/etcd /etcd -adr=172.17.42.1:4001 -bind-addr=0.0.0.0:4001
```
or
```sh
docker run -p 4001:4001 -d coreos/etcd /etcd -adr=172.17.42.1:4001 -bind-addr=172.17.42.1:4001
```
or
 ```sh
docker run -p 4001:4001 -d coreos/etcd /etcd -adr=172.17.42.1:4001
```

in app container:
```sh
# curl 172.17.42.1:4001/version
etcd 0.4.6
```
but in any case of etcd statup command I have:
```sh
# confd --version
confd 0.10.0

# confd -onetime -node 172.17.42.1:4001 
2015-08-25T11:01:09Z 774f032c9d18 confd[187]: INFO Backend set to etcd
2015-08-25T11:01:09Z 774f032c9d18 confd[187]: INFO Starting confd
2015-08-25T11:01:09Z 774f032c9d18 confd[187]: INFO Backend nodes set to 172.17.42.1:4001
2015-08-25T11:01:09Z 774f032c9d18 confd[187]: ERROR 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/keystone/hosts/public?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused]) [0]
```

From this topic it's not clear for me how to fix this

**Comment by agalitsyn** [comment]
So, I upgrade to latest etcd 2.1.2 and run it with `docker run quay.io/coreos:latest -p 4001:4001 -advertise-client-urls http://172.17.42.1:4001 -listen-client-urls http://0.0.0.0:4001`. It solves my problem.

**Comment by balboah** [comment]
Still having this problem when trying locally via docker-compose:

```
etcd_1         | 2015/10/14 06:57:47 etcdserver: added local member ce2a822cea30bfca [http://localhost:2380 http://localhost:7001] to cluster 7e27652122e8b2ae
loadbalancer_1 | + ETCD=etcd
loadbalancer_1 | + rsyslogd
loadbalancer_1 | + /usr/local/bin/confd -node=http://etcd:4001 -watch=true -log-level=debug
loadbalancer_1 | 2015-10-14T06:57:47Z 1a0e40a29fbc /usr/local/bin/confd[15]: INFO Backend set to etcd
loadbalancer_1 | 2015-10-14T06:57:47Z 1a0e40a29fbc /usr/local/bin/confd[15]: INFO Starting confd
loadbalancer_1 | 2015-10-14T06:57:47Z 1a0e40a29fbc /usr/local/bin/confd[15]: INFO Backend nodes set to http://etcd:4001
loadbalancer_1 | 2015-10-14T06:57:47Z 1a0e40a29fbc /usr/local/bin/confd[15]: DEBUG Loading template resources from confdir /etc/confd
loadbalancer_1 | 2015-10-14T06:57:47Z 1a0e40a29fbc /usr/local/bin/confd[15]: DEBUG Loading template resource from /etc/confd/conf.d/haproxy.toml
loadbalancer_1 | 2015-10-14T06:57:47Z 1a0e40a29fbc /usr/local/bin/confd[15]: ERROR 501: All the given peers are not reachable (failed to propose on members [] twice [last error: Get /v2/keys/?quorum=false&recursive=true&sorted=false: unsupported protocol scheme ""]) [0]
etcd_1         | 2015/10/14 06:57:48 raft: ce2a822cea30bfca is starting a new election at term 1
etcd_1         | 2015/10/14 06:57:48 raft: ce2a822cea30bfca became candidate at term 2
etcd_1         | 2015/10/14 06:57:48 raft: ce2a822cea30bfca received vote from ce2a822cea30bfca at term 2
etcd_1         | 2015/10/14 06:57:48 raft: ce2a822cea30bfca became leader at term 2
etcd_1         | 2015/10/14 06:57:48 raft.node: ce2a822cea30bfca elected leader ce2a822cea30bfca at term 2
etcd_1         | 2015/10/14 06:57:48 etcdserver: published {Name:default ClientURLs:[http://etcd:4001]} to cluster 7e27652122e8b2ae
loadbalancer_1 | 2015-10-14T06:57:49Z 1a0e40a29fbc /usr/local/bin/confd[15]: ERROR 501: All the given peers are not reachable (failed to propose on members [] twice [last error: Get /v2/keys/?quorum=false&recursive=true&sorted=false: unsupported protocol scheme ""]) [0]
loadbalancer_1 | 2015-10-14T06:57:51Z 1a0e40a29fbc /usr/local/bin/confd[15]: ERROR 501: All the given peers are not reachable (failed to propose on members [] twice [last error: Get /v2/keys/?quorum=false&recursive=true&sorted=false: unsupported protocol scheme ""]) [0]
loadbalancer_1 | 2015-10-14T06:57:53Z 1a0e40a29fbc /usr/local/bin/confd[15]: ERROR 501: All the given peers are not reachable (failed to propose on members [] twice [last error: Get /v2/keys/?quorum=false&recursive=true&sorted=false: unsupported protocol scheme ""]) [0]
```

Seems like it gets stuck forever if confd connected before etcd elected itself as leader.
If however the etcd was already running, it works fine.

Versions:
confd 0.10.0
etcd 2.1.2

**Comment by moshe0076** [comment]
Changing "-advertise-client-urls" from http://0.0.0.0:4001 to http://etcd-server-ip-address:4001 have solved the problem of  confd connecting to this remote etcd and giving me  "dial tcp 0.0.0.0:4001: connection refused".

**Comment by hardywu** [comment]
Still see this error.

**Comment by krish7919** [comment]
Me too, still see this error in v0.11

**Comment by ehudkaldor** [comment]
had the same thing and Moshe's solution above solved it. it seems like at the first access to etcd it grabs the listen address and then, it tries to use that address to connect to etcd again. if the listen address is set as 0.0.0.0, it tries to connect to it. stating the real address solves it.
as my IP is dynamic, I use this scriptlet:
```
ip=$(ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')
echo "$ip is alive !"

#etcd --name ${HOSTNAME} --advertise-client-urls 'http://0.0.0.0:2379,http://0.0.0.0:4001' --listen-client-urls 'http://0.0.0.0:2379,http://0.0.0.0:4001' --data-dir /var/etcd 
etcd --name ${HOSTNAME} --advertise-client-urls "http://$ip:2379,http://$ip:4001" --listen-client-urls "http://$ip:2379,http://$ip:4001" --data-dir /var/etcd

```

**Comment by liudajiang3** [comment]
had the same,moshe and ehudkaldor advice is helpful. another solution is change v0.15
